"""Job expiration

Revision ID: 2d521b9b56c8
Revises: 58bbb1d51897
Create Date: 2025-07-10 14:22:15.993190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d521b9b56c8'
down_revision: Union[str, None] = '58bbb1d51897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('on_expiry_action', sa.Enum('CREATE_NOTIFY_JOB', name='onexpiryaction'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'on_expiry_action')
    op.drop_column('jobs', 'expires_at')
    # ### end Alembic commands ###
