[project]
name = "misho-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ivo Petkovic", email = "ivo.petkovic@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "misho-client",
    "openai>=1.91.0",
    "python-telegram-bot>=22.1",
]

[project.scripts]
misho-bot = "misho_bot:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
misho-client = { workspace = true }
